name: Cron every day

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true
        
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    container:
      image: ghcr.io/hoangsoft90/bckcron:latest
      credentials:
         username: hoangsoft90
         password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@master
    
    - name: Run backup
      if: success()
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        ghcr.io/hoangsoft90/bckcron:latest
