name: Cron every day

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    
    steps:
    - uses: actions/checkout@master
    
    - name: docker registry login
      run: echo ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }} | docker login ghcr.io --username hoangsoft90 --password-stdin

    - name: Run check
      if: success()
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        ghcr.io/hoangsoft90/bckcron:latest
